---
Name: uniads_config
---
Page:
  extensions:
    - 'SilverstripeUniads\Extension\UniadsPageExtension'
SilverstripeUniads\Model\UniadsObject:
  use_js_tracking: true
  record_impressions: true
  record_impressions_stats: false
  record_clicks: true
  record_clicks_stats: true
  files_dir: 'UploadedAds'
  max_file_size: 2097152
  allow_flash: false
  # this allows you to override and configure your own URL
  # If you use your own jquery, the block this URL
  jquery_url: 'https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js'
  jquery_sri: 'sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8='
SilverstripeUniads\Model\UniadsImpression:
  store_user_agent: true
SilverstripeUniads\Jobs\UniAdsReportJob:
  interval: 24
